spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contatos
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 17527
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect